version: "1.0"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_PASSWORD: ""
      DB_USERNAME: ""
      DB_HOST: ""
      SCOPE: ""