version: "3.5"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "3306:3306"
    environment:
      DB_PASSWORD: ""
      DB_USERNAME: "root"
      DB_HOST: "host.docker.internal"
      SCOPE: "develop-write"